name: "Keycloak for Home Assistant Beta"
description: "Keycloak addon for Home Assistant"
version: "0.0.2"
slug: "keycloak_for_home_assistant-beta"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: "services"
boot: "auto"
image: "local/keycloak"
ports:
  8080/tcp: 8080
  8443/tcp: 8443
environment:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMINPASSWORD: "admin"
ingress: false
host_network: false
