name: "Keycloak for Home Assistant Beta"
description: "Keycloak addon for Home Assistant"
version: "0.0.5"
slug: "keycloak_for_home_assistant-beta"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: "services"
boot: "auto"
ports:
  8080/tcp: 8080
  8443/tcp: 8443
environment:
  KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
  KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
ingress: false
host_network: false
init: false
