name: Tag on Renovate Merge

on:
  push:
    branches:
      - main

jobs:
  tag_on_renovate:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'chore(deps)')"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Ensure full history is available for tags

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Bump version to stable config.yml
        run: |
          file="keycloak-for-home-assistant/config.yaml"
          if [ ! -f "$file" ]; then echo "Missing config.yaml in stable."; exit 1; fi
          
          OLD_VERSION=$(yq '.version' "$file" | tr -d '"')
          IFS='.' read -r MAJOR MINOR PATCH <<< "$OLD_VERSION"
          NEW_VERSION="$MAJOR.$MINOR.$((PATCH+1))"

          yq -i ".version = \"$NEW_VERSION\"" "$file"

          echo "Old version: $OLD_VERSION"
          echo "New version: $NEW_VERSION"
      - name: Bump version to beta config.yml
        run: |
          file="keycloak-for-home-assistant-beta/config.yaml"
          if [ ! -f "$file" ]; then echo "Missing config.yaml in beta."; exit 1; fi
          
          OLD_VERSION=$(yq '.version' "$file" | tr -d '"')
          IFS='.' read -r MAJOR MINOR PATCH <<< "$OLD_VERSION"
          NEW_VERSION="$MAJOR.$MINOR.$((PATCH+1))"

          yq -i ".version = \"$NEW_VERSION\"" "$file"

          echo "Old version: $OLD_VERSION"
          echo "New version: $NEW_VERSION"


      - name: Commit and push changes
        run: |
          git add keycloak-for-home-assistant/
          git add keycloak-for-home-assistant-beta/
          git commit -m "chore: promote beta to stable with version bump"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get current version from stable config.yaml
        id: get_version
        run: |
          version=$(yq '.version' keycloak-for-home-assistant/config.yaml | tr -d '"')
          echo "VERSION=$version" >> $GITHUB_OUTPUT
      - name: Create Git tag
        run: |
          git tag -a "v${{ steps.get_version.outputs.VERSION }}" -m "Release v${{ steps.get_version.outputs.VERSION }}"
          git push origin "v${{ steps.get_version.outputs.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          name: Release v${{ steps.get_version.outputs.VERSION }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
