name: Tag on Renovate Merge

on:
  push:
    branches:
      - main

jobs:
  tag_on_renovate:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'chore(deps)')"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is available for tags

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get current version from stable config.yaml
        id: get_version
        run: |
          OLD_VERSION=$(yq '.version' keycloak-for-home-assistant/config.yaml | tr -d '"')
          
          IFS='.' read -r MAJOR MINOR PATCH <<< "$OLD_VERSION"
          version="$MAJOR.$MINOR.$((PATCH+1))"
          
          echo "VERSION=$version" >> $GITHUB_OUTPUT

      - name: Create Git tag
        run: |
          git tag -a "v${{ steps.get_version.outputs.VERSION }}" -m "Release v${{ steps.get_version.outputs.VERSION }}"
          git push origin "v${{ steps.get_version.outputs.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          name: Release v${{ steps.get_version.outputs.VERSION }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
